apiVersion: v2
name: conductor-oss-conductor
description: Chart for deploying a Conductor OSS Conductor on Kubernetes as Deployment
type: application
version: 3.15.0
appVersion: "3.15.0"
keywords:
  - conductor
maintainers:
  - name: dradoaica
    email: dradoaica@gmail.com
kubeVersion: ">= 1.26.0"
