apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-oss-conductor.fullname" . }}
  labels:
    {{- include "conductor-oss-conductor.labels" . | nindent 4 }}
  {{- with (include "conductor-oss-conductor.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  elasticsearch-password: {{ .Values.secrets.elasticsearchPassword | b64enc | quote }}
