apiVersion: v1
kind: Service
metadata:
  name: {{ include "conductor-oss-conductor.fullname" . }}
  labels:
    {{- include "conductor-oss-conductor.labels" . | nindent 4 }}
spec:
  ports:
    - name: ui
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  clusterIP: None
  selector:
    {{- include "conductor-oss-conductor.selectorLabels" . | nindent 4 }}
