apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-config-map
data:
  ignite-config.conf: |
    {
      ignite: {
        network: {
          # Ignite 3 node port
          port: 3344,
          nodeFinder: {
            netClusterNodes: [
              # Kubernetes service to access the Ignite 3 cluster on the Kubernetes network
              "{{ include "ignite.fullname" . }}-svc-headless:3344"
            ]
          }
        }
      }
    }
