# Default values for ignite.
replicaCount: 2

image:
  repository: apacheignite/ignite
  tag: 2.17.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  name:

dataStorage:
  config: |-

metrics:
  enabled: false

env:
  OPTION_LIBS: "ignite-kubernetes,ignite-rest-http,ignite-json,ignite-opencensus"
  IGNITE_QUIET: "false"
  IGNITE_WAL_MMAP: "false"
  IGNITE_WAIT_FOR_BACKUPS_ON_SHUTDOWN: "true"
  JVM_OPTS: "-Djava.net.preferIPv4Stack=true -Xms1g -Xmx1g -server -XX:MaxMetaspaceSize=256m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC"
peerClassLoadingEnabled: false

## envFrom can be used to pass config-maps or secrets as environment
# envFrom:
#   - configMapRef:
#       name: env-config-maps
#   - secretRef:
#       name: env-secrets

## Additional init containers to run before the pods.
## for example, be used to run a sidecar that chown Logs storage .
extraInitContainers: []
#  - name: volume-mount-hack
#    image: busybox
#    command: ["sh", "-c", "chown -R 1000:1000 logs"]

## Additional containers to run alongside the pods
## This could, for example, be used to run jmx-exporter
extraContainers: []
#  - name: jmxexporter
#    image: sscaling/jmx-prometheus-exporter
#    command: ["sh", "-c", "chown -R 1000:1000 logs"]

persistence:
  enabled: false
  persistenceVolume:
    size: 8Gi
    provisioner: kubernetes.io/aws-ebs
    provisionerParameters:
      type: gp2
      fsType: ext4
  walVolume:
    size: 8Gi
    provisioner: kubernetes.io/aws-ebs
    provisionerParameters:
      type: gp2
      fsType: ext4

## extraVolumes and extraVolumeMounts allows you to mount other volumes
## Example Use Cases:
##  mount certificates to enable tls
extraVolumes:
# - name: ignite-keystore
#   secret:
#     defaultMode: 288
#     secretName: ignite-keystore
# - name: ignite-trustsore
#   secret:
#     defaultMode: 288
#     secretName: ignite-truststore
# extraVolumeMounts:
# - name: ignite-keystore
#   mountPath: /certs/keystore
#   readOnly: true
# - name: ignite-truststore
#   mountPath: /certs/truststore
#   readOnly: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""
