global:
  imageRegistry: ""

nameOverride: ""
fullnameOverride: ""

commonAnnotations: { }
labels: { }
podLabels: { }
podAnnotations: { }
customLabels: { }

extraInitContainers: [ ]
extraContainers: [ ]
extraVolumes: [ ]
extraVolumeMounts: [ ]
extraEnvVars: [ ]
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
envFrom: [ ]

image:
  registry: docker.io
  repository: apacheignite/ignite
  tag: 3.1.0
  pullPolicy: IfNotPresent
  pullSecrets: [ ]
  debug: false

serviceAccount:
  create: true
  name: ""
  annotations: { }

rbac:
  create: true

podManagementPolicy: OrderedReady
revisionHistoryLimit: 10

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partition: 0

priorityClassName: ""

terminationGracePeriodSeconds: 60

podSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: "2"
    memory: 4Gi
  limits:
    cpu: "2"
    memory: 4Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /management/v1/node/state
    port: 10300
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /management/v1/node/state
    port: 10300
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  httpGet:
    path: /management/v1/node/state
    port: 10300
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 15
  successThreshold: 1

service:
  ports:
    management: 10300
    rest: 10800
    cluster: 3344

persistence:
  enabled: true
  size: 10Gi
  storageClass: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce

nodeSelector: { }
tolerations: [ ]
affinity: { }
topologySpreadConstraints: [ ]

# App specific
replicaCount: 1

jmx:
  enabled: false
  port: 9404
  agent:
    image:
      registry: docker.io
      repository: busybox
      tag: 1.36
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  config: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true

env:
  JVM_MAX_MEM: "4g"
  JVM_MIN_MEM: "4g"

initializationJob:
  enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi
